# Data format, 'presto' or 'sigproc'
data_format: presto

# Number of time series searched in parallel
num_processes: 16

# Max value of DM x |sin(b)|. Sets an upper limit on DM trials as a function
# of observed sky coordinates. If left blank, no upper limit is applied.
dmsinb_max: 40.0

# Hard DM trial limits, regardless of sky coordinates
# These fields can be left blank, in which case the associated limit is not
# applied.
dm_min: 0.0
dm_max: 

# Minimum difference between consecutive DM trials
dm_step: 0.05

# Paths to configuration files for the searches. They must be placed in the
# same directory as this file.
search_configs:

##### Candidate filtering
# The cap on candidate number is applied last, after all the other filters
# These fields can be left empty, in which case the corresponding filter is
# not applied
candidate_filters:
    dm_min: 1.0
    snr_min: 8.0
    max_number: 100