# Configuration files designed to search 6-hour deep pointings
# of the Small Magellanic Cloud (SMC).

# Data format, 'presto' or 'sigproc'
data_format: presto

# Number of time series searched in parallel
num_processes: 12

# Max value of DM x |sin(b)|. Sets an upper limit on DM trials as a function
# of observed sky coordinates. If left blank, no upper limit is applied.
dmsinb_max:

# Hard DM trial limits, regardless of sky coordinates
# These fields can be left blank, in which case the associated limit is not
# applied.
dm_min: 0.0
dm_max: 400.0

# Minimum difference between consecutive DM trials
dm_step: 2.0

# Paths to configuration files for the searches. They must be placed in the
# same directory as this file.
search_configs: 
  - config_short.yaml
  - config_medium.yaml
  - config_long.yaml

##### Candidate filtering
# The cap on candidate number is applied last, after all the other filters
# These fields can be left empty, in which case the corresponding filter is
# not applied
candidate_filters:
  dm_min:
  snr_min:
  max_number: 1000
