### Input data format. 'presto' or 'sigproc' only for now.
data_format: presto

### Controls the DM trial spacing and ultimately which time series
### are chosen for processing, and which ones are skipped to save time
ddplan:
    # Observing bandwidth parameters
    fmin: 119.434
    fmax: 151.075
    nchans: 2592

    # Max value of DM x |sin(b)|. Sets an upper limit on DM trials as a function
    # of observed sky coordinates
    dmsinb_max: 40.0

    # Hard DM trial limit, regardless of sky coordinates
    dm_min: 0.0
    dm_max: 600.0

### Keyword arguments to the ffa_search() function ###
search:
    period_min: 0.80
    period_max: 60.0
    bins_min: 250
    bins_max: 270
    fpmin: 10
    rmed_width: 4.0
    rmed_minpts: 101
    wtsp: 1.5
    threads: 1

### Keyword arguments to the find_peaks() function ###
peak_detection:
    segment_dftbins_length: 30.0
    min_segments: 8
    snr_min: 7.0
    nsigma: 7.0
    peak_clustering_radius: 0.20
    polydeg: 2

### Candidate parameters ###
candidates:
    # Number of phase bins. Make sure that period_min / sampling_time is
    # larger than this number.
    nbins: 512

    # NOTE: this specifies only a maximum number of sub-integrations. Some
    # of the longer period candidates may end up with less sub-integrations:
    # exactly one per period.
    nsubs: 128
