data_format: presto
num_processes: 4

# Max value of DM x |sin(b)|. Sets an upper limit on DM trials as a function
# of observed sky coordinates
dmsinb_max: 40.0

# Hard DM trial limits, regardless of sky coordinates
dm_min: 0.0
dm_max: 1000.0

# Minimum difference between consecutive DM trials
dm_step: 4.0

### Configuration files for the searches, to be placed in the same directory
search_configs:
    - search_config.yaml
