# Data format, 'presto' or 'sigproc'
data_format: presto

# Minimum and Maximum observing frequencies in MHz
fmin: 1181.0
fmax: 1581.0

# Number of time series searched in parallel
num_processes: 4

# Max value of DM x |sin(b)|. Sets an upper limit on DM trials as a function
# of observed sky coordinates
# If left empty, no upper limit is applied
dmsinb_max: 40.0

# Hard DM trial limits, regardless of sky coordinates
dm_min: 0.0
dm_max: 1000.0

# Minimum difference between consecutive DM trials
dm_step: 1.0

##### Paths to configuration files for the searches
# NOTE: they must be placed in the same directory as this file.
search_configs:
    - search_config.yaml

### Harmonic filtering
harmonic_filtering:
    max_denominator: 30
    max_distance: 1.0
    snr_tol: 1.5

##### Candidate filtering
# The cap on candidate number is applied last, after all the other filters
# These fields can be left empty, in which case the corresponding filter is
# not applied
candidate_filters:
    dm_min: 1.0
    snr_min: 8.0
    max_number: 100
